Waiting for a ready msg from server
nilenso/time-tracker-web pull request #15
Opened 2017-07-06 12:11 UTC by trycatcher

Server now sends a "Ready frame" when the on-recive Callback hooks up after which messages can safely be sent by the Client.This addresses http-kit/http-kit#318

2017-07-07 04:35 UTC, jysandy requested changes

2017-07-07 04:35 UTC, jysandy commented on src/thunks.js
> +        if (message['auth-status'] === 'success') {
@trycatcher here if the first message is a `success` message and not a ready frame, the connection will still be considered authenticated and ready, even though the client never sent an authentication message.

Although this 'works', I think our implementation ought to be more correct. The client should only wait for the authentication success message after it has received the `ready` message and sent the `authenticate` message. Here's a state diagram to clarify:

waiting for ready frame --> waiting for authentication success --> receiving data messages

2017-07-07 06:08 UTC, trycatcher commented on src/thunks.js
> +        if (message['auth-status'] === 'success') {
@jysandy Changed in line with the state diagram. Additionally, if the first message is not a "Ready" the connection is closed. https://github.com/nilenso/time-tracker-web/blob/11a09e62beb247c88ce745964ddc55fadbdf5c92/src/thunks.js

2017-07-07 06:12 UTC, trycatcher commented
@jysandy Pushed the change for this https://github.com/nilenso/time-tracker-web/pull/15/commits/11a09e62beb247c88ce745964ddc55fadbdf5c92

2017-07-10 05:05 UTC, jysandy requested changes

2017-07-10 05:05 UTC, jysandy commented on src/thunks.js
> +        wsConnection.close();
@trycatcher you should `dispatch(wsHandshakeFailed())` here, just like on line 79.

2017-07-10 05:06 UTC, jysandy commented
@trycatcher once you make that super small change I'm actually OK with this being merged, so go ahead and merge this and https://github.com/nilenso/time-tracker/pull/82 after you make the change.

2017-07-10 05:09 UTC, jysandy commented
As a bit of an aside: Redefining the callback is easy to understand if the connection doesn't have too many states. Another way of implementing this would have been to add a state variable, which can maybe take values like `WAITING_FOR_READY_MESSAGE` or `WAITING_FOR_AUTH_RESPONSE`, etc, and then in the callback just `switch` on that variable and do the appropriate thing. Fairly straightforward way of implementing a state machine.

2017-07-10 06:32 UTC, trycatcher commented
@jysandy Added the dispatch. Will go ahead merging this and https://github.com/nilenso/time-tracker/pull/82

2017-07-10 06:33 UTC, trycatcher commented
@jysandy I'm in favor of making the state transition explicit over redefining callbacks. I'll add a low-priority tech card so that we can come back and do it.

2017-07-10 06:43 UTC, merged